Project Threaddit {
    database_type: 'PostgreSQL'
    Note: "This is Threaddit's database schema."
}

Enum "MediaType" {
  "IMAGE"
  "VIDEO"
  "URL"
}

Table "alembic_version" {
  "version_num" VARCHAR(32) [not null]

  Indexes {
    version_num [pk, name: "alembic_version_pkc"]
  }
}

Table "media" {
  "media_id" SERIAL [not null, increment]
  "name" TEXT [not null]
  "media_type" MediaType [not null]
  "url" TEXT [not null]
  "cldr_id" TEXT
  "is_nsfw" BOOLEAN [not null, default: false]
  "is_spoiler" BOOLEAN [not null, default: false]
  "created_on" TIMESTAMP [not null, default: `now()`]
  "updated_on" TIMESTAMP

  Indexes {
    media_id [pk]
  }
}
