"""Create Messages Table.

Revision ID: 39c99b6cae46
Revises: a4884e521e04
Create Date: 2024-07-07 18:34:46.295043

"""  # noqa: INP001

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "39c99b6cae46"
down_revision = "a4884e521e04"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("message_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("receiver_id", sa.Integer(), nullable=False),
        sa.Column("media_id", sa.Integer(), nullable=True),
        sa.Column("encrypted_content", sa.TEXT(), nullable=False),
        sa.Column("created_on", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("seen_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_on", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint("encrypted_content ~* '[^\\s]+'"),
        sa.CheckConstraint("num_nonnulls(encrypted_content, media_id) >= 1"),
        sa.ForeignKeyConstraint(["media_id"], ["media.media_id"], onupdate="cascade", ondelete="set null"),
        sa.ForeignKeyConstraint(["receiver_id"], ["users.user_id"], onupdate="cascade", ondelete="restrict"),
        sa.ForeignKeyConstraint(["sender_id"], ["users.user_id"], onupdate="cascade", ondelete="restrict"),
        sa.PrimaryKeyConstraint("message_id"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_messages_sender_id"), ["sender_id", "receiver_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_sender_id"))

    op.drop_table("messages")
    # ### end Alembic commands ###
