"""Create Threads Table.

Revision ID: 8bab6766e701
Revises: bbffc7376c38
Create Date: 2024-07-07 16:08:31.663110

"""  # noqa: INP001

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8bab6766e701"
down_revision = "bbffc7376c38"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "threads",
        sa.Column("thread_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=16), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column(
            "flairs", postgresql.ARRAY(sa.VARCHAR(length=16), zero_indexes=True), server_default="{}", nullable=False
        ),
        sa.Column(
            "join_message",
            sa.VARCHAR(length=256),
            server_default="Welcome to the Thread, Check the rules.",
            nullable=False,
        ),
        sa.Column("post_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("comment_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("subscription_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_locked", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_nsfw", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_banned", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_private", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("logo_id", sa.Integer(), nullable=True),
        sa.Column("banner_id", sa.Integer(), nullable=True),
        sa.Column("created_on", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_on", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint("name ~* '^\\w{3,16}$'"),
        sa.CheckConstraint("array_ndims(flairs) = 1 AND array_length(flairs, 1) <= 16"),
        sa.ForeignKeyConstraint(["banner_id"], ["media.media_id"], onupdate="cascade", ondelete="set null"),
        sa.ForeignKeyConstraint(["creator_id"], ["users.user_id"], onupdate="cascade", ondelete="restrict"),
        sa.ForeignKeyConstraint(["logo_id"], ["media.media_id"], onupdate="cascade", ondelete="set null"),
        sa.PrimaryKeyConstraint("thread_id"),
    )
    with op.batch_alter_table("threads", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_threads_name"), ["name"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("threads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_threads_name"))

    op.drop_table("threads")
    # ### end Alembic commands ###
