"""Create Saves Table.

Revision ID: a4884e521e04
Revises: c089a56d4580
Create Date: 2024-07-07 18:31:22.044298

"""  # noqa: INP001

import sqlalchemy as sa
import sqlalchemy_searchable
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4884e521e04'
down_revision = 'c089a56d4580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saves',
    sa.Column('save_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.comment_id'], onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('save_id')
    )
    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saves_creator_id'), ['creator_id', 'post_id', 'comment_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saves_creator_id'))

    op.drop_table('saves')
    # ### end Alembic commands ###
