"""Media references users.

Revision ID: bbffc7376c38
Revises: a0cc4a101085
Create Date: 2024-07-07 15:35:08.143506

"""  # noqa: INP001

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bbffc7376c38"
down_revision = "a0cc4a101085"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media", schema=None) as batch_op:
        batch_op.add_column(sa.Column("creator_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            "media_creator_id_fkey", "users", ["creator_id"], ["user_id"], ondelete="restrict", onupdate="cascade"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media", schema=None) as batch_op:
        batch_op.drop_constraint("media_creator_id_fkey", type_="foreignkey")
        batch_op.drop_column("creator_id")

    # ### end Alembic commands ###
