"""Create Votes Table.

Revision ID: c089a56d4580
Revises: b52c9afabf50
Create Date: 2024-07-07 18:24:58.257485

"""  # noqa: INP001

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c089a56d4580"
down_revision = "b52c9afabf50"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "votes",
        sa.Column("vote_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("comment_id", sa.Integer(), nullable=True),
        sa.Column("vote_type", postgresql.ENUM("UPVOTE", "DOWNVOTE", name="VoteType"), nullable=False),
        sa.Column("created_on", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_on", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["comment_id"], ["comments.comment_id"], onupdate="cascade", ondelete="restrict"),
        sa.ForeignKeyConstraint(["creator_id"], ["users.user_id"], onupdate="cascade", ondelete="restrict"),
        sa.ForeignKeyConstraint(["post_id"], ["posts.post_id"], onupdate="cascade", ondelete="restrict"),
        sa.PrimaryKeyConstraint("vote_id"),
    )
    with op.batch_alter_table("votes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_votes_post_id"), ["post_id", "creator_id", "comment_id"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("votes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_votes_post_id"))

    sa.Enum(name="VoteType").drop(op.get_bind(), checkfirst=False)

    op.drop_table("votes")
    # ### end Alembic commands ###
