"""Create Media Table, Setup Searchable.

Revision ID: de09ea700177
Revises:
Create Date: 2024-07-01 21:47:09.920409

"""  # noqa: INP001

import sqlalchemy as sa
import sqlalchemy_searchable
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "de09ea700177"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sqlalchemy_searchable.sql_expressions.statement)

    op.create_table(
        "media",
        sa.Column("media_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("media_type", postgresql.ENUM("IMAGE", "VIDEO", "URL", name="MediaType"), nullable=False),
        sa.Column("url", sa.TEXT(), nullable=False),
        sa.Column("cldr_id", sa.TEXT(), nullable=True),
        sa.Column("is_nsfw", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_spoiler", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_on", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_on", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint("name ~* '^[\\w\\s-]+\\.\\w{3,}$'"),
        sa.CheckConstraint("url ~* '^(https?:\\/\\/)?(www\\.)?([\\w.]+\\.\\w+).*\\/([\\w\\s-]+\\.\\w{3,})$'"),
        sa.PrimaryKeyConstraint("media_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("media")
    sa.Enum(name="MediaType").drop(op.get_bind(), checkfirst=False)

    op.execute("DROP FUNCTION parse_websearch(regconfig, text);")
    op.execute("DROP FUNCTION parse_websearch(text);")
    # ### end Alembic commands ###
